version: '3.5'

services:
  postgres:
    container_name: madkudu_pg
    image: postgres
    environment:
      POSTGRES_USER: mgaudin
      POSTGRES_PASSWORD: MG44901
      POSTGRES_DB: madkudu
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

volumes:
  postgres: